### ISSUE TITLE
cannot reproduce your experiment result

### ISSUE THREAD

**Issue by dolortaste** [HopLee6/SSPVS-PyTorch#1]
I ran your code on summe-c.cfg and summe-c-tg.cfg using your provided pretrained checkpoint and get the result:
![image](https://user-images.githubusercontent.com/6359718/207216719-69715b2a-dd55-4277-b369-3cd53bb46e3f.png)

**Comment by fazlicodes** [comment]
@dolortaste were you able to reproduce the results
